name: Build EXE

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:  # Дозволяє запускати збірку вручну кнопкою

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      # Ця команда встановить всі бібліотеки з pyproject.toml, включаючи PyInstaller
      - name: Install dependencies
        run: uv sync

      # Збірка. --collect-all важливий для тем оформления (qt_material)
      - name: Build with PyInstaller
        run: |
          uv run pyinstaller --noconfirm --onefile --windowed --name "HabitTracker" --collect-all qt_material main.py

      # Завантаження готового файлу в Artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HabitTracker-exe
          path: dist/HabitTracker.exe